# Generated by Django 5.0 on 2024-02-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_generator", "0002_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Additionals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="additionals",
            field=models.ManyToManyField(to="blog_generator.additionals"),
        ),
    ]
